steps:
- name: 'gcr.io/support-tools-299121/graalvm'
  args: ['./mvnw', 'package', '-Pnative']
- name: 'bash'
  args: ['mv', 'target/http-wrapper-*-SNAPSHOT-runner', 'hwrap']
artifacts:
  objects:
    location: 'gs://nklab-artifacts/'
    paths: ['hwrap']
