steps:
- name: golang
  id: Init
  args: ['go', 'mod', 'download']
- name: golang
  id: Build
  args: ['go', 'build', '.']
artifacts:
  objects:
    location: 'gs://nklab-artifacts/'
    paths: ['hwrap']
